# must be unique in a given SonarQube Server instance
sonar.projectKey=go-ci

# --- optional properties ---
#sonar.sources=.
sonar.exclusions=**/*_test.go
#sonar.test.inclusions=**/*_test.go
#sonar.host.url=http://localhost:9000
# sonar.token=sqp_60b1de16bf07eb586abb2d803b341dfaa3b72951
# sonar.go.coverage.reportPaths=coverage.out